### ISSUE TITLE
Use this library with react-router v6

### ISSUE THREAD

**Issue by nowiko** [robberfree/keep-alive-route#1]
Hi,
Could this package be used with react-router v6?
When I am trying to use it I am getting a lot of errors, like:
`... is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>`
and
`useRouteMatch is not a function`

**Comment by robberfree** [comment]
Maybe it's possible. I haven't use the react-router v6 yet. I will have a try sometimes.
Free to make PR.

**Comment by nowiko** [comment]
As this issue is not relevant to me, so I mark it as closed.
